const fs = require('fs');

class ChartGenerator {
  static generateBarChart(title, data, yLabel, filename) {
    const width = 800;
    const height = 500;
    const padding = { top: 80, right: 40, bottom: 80, left: 80 };
    const chartWidth = width - padding.left - padding.right;
    const chartHeight = height - padding.top - padding.bottom;

    const maxVal = Math.max(...Object.values(data), 1);
    const yMax = Math.ceil(maxVal * 1.15); // Add 15% headroom
    const algorithms = Object.keys(data);
    const barWidth = Math.min(100, chartWidth / algorithms.length - 40);

    let svg = `<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" style="background-color:#0f172a; font-family: 'Inter', system-ui, sans-serif;">\n`;
    
    // Definitions for gradients and shadows
    svg += `<defs>
      <linearGradient id="gradACPA" x1="0%" y1="0%" x2="0%" y2="100%">
        <stop offset="0%" style="stop-color:#3b82f6;stop-opacity:1" />
        <stop offset="100%" style="stop-color:#1e40af;stop-opacity:1" />
      </linearGradient>
      <linearGradient id="gradFIFO" x1="0%" y1="0%" x2="0%" y2="100%">
        <stop offset="0%" style="stop-color:#94a3b8;stop-opacity:1" />
        <stop offset="100%" style="stop-color:#475569;stop-opacity:1" />
      </linearGradient>
      <linearGradient id="gradPriority" x1="0%" y1="0%" x2="0%" y2="100%">
        <stop offset="0%" style="stop-color:#f59e0b;stop-opacity:1" />
        <stop offset="100%" style="stop-color:#b45309;stop-opacity:1" />
      </linearGradient>
      <filter id="drop-shadow" x="-20%" y="-20%" width="140%" height="140%">
        <feDropShadow dx="0" dy="4" stdDeviation="4" flood-color="#000000" flood-opacity="0.3"/>
      </filter>
    </defs>\n`;

    // Title and Subtitle
    svg += `<text x="${width/2}" y="40" text-anchor="middle" font-size="24" font-weight="bold" fill="#f8fafc">${title}</text>\n`;
    svg += `<text x="${width/2}" y="60" text-anchor="middle" font-size="14" fill="#94a3b8">SCOS ACPA Experimental Benchmark Results</text>\n`;
    
    // Y-Axis Label
    svg += `<text x="25" y="${height/2}" text-anchor="middle" font-size="14" font-weight="600" fill="#cbd5e1" transform="rotate(-90, 25, ${height/2})">${yLabel}</text>\n`;

    // Y-Axis Grid Lines & Labels
    const steps = 5;
    for (let i = 0; i <= steps; i++) {
      const val = (yMax / steps) * i;
      const y = height - padding.bottom - (val / yMax) * chartHeight;
      svg += `<line x1="${padding.left}" y1="${y}" x2="${width-padding.right}" y2="${y}" stroke="#334155" stroke-width="1" stroke-dasharray="4,4"/>\n`;
      svg += `<text x="${padding.left-15}" y="${y+5}" text-anchor="end" font-size="12" fill="#94a3b8">${Math.round(val)}</text>\n`;
    }

    // Baseline (X-Axis)
    svg += `<line x1="${padding.left}" y1="${height-padding.bottom}" x2="${width-padding.right}" y2="${height-padding.bottom}" stroke="#cbd5e1" stroke-width="2"/>\n`;

    // Bars
    algorithms.forEach((algo, idx) => {
      const val = data[algo];
      const barHeight = (val / yMax) * chartHeight;
      const spacing = chartWidth / algorithms.length;
      const x = padding.left + (spacing / 2) - (barWidth / 2) + (idx * spacing);
      const y = height - padding.bottom - barHeight;

      let fill = 'url(#gradACPA)'; // blue for ACPA
      let textColor = '#60a5fa';
      if (algo === 'FIFO') { fill = 'url(#gradFIFO)'; textColor = '#cbd5e1'; }
      if (algo === 'Priority') { fill = 'url(#gradPriority)'; textColor = '#fbbf24'; }

      // Bar with shadow
      svg += `<rect x="${x}" y="${y}" width="${barWidth}" height="${barHeight}" fill="${fill}" rx="6" filter="url(#drop-shadow)"/>\n`;
      
      // Value Label on top of bar
      svg += `<text x="${x + barWidth/2}" y="${y - 12}" text-anchor="middle" font-size="16" font-weight="bold" fill="${textColor}">${Math.round(val)}</text>\n`;
      
      // X-Axis Label
      svg += `<text x="${x + barWidth/2}" y="${height - padding.bottom + 25}" text-anchor="middle" font-size="16" font-weight="bold" fill="#f8fafc">${algo}</text>\n`;
    });

    // Branding / Watermark
    svg += `<text x="${width - 15}" y="${height - 15}" text-anchor="end" font-size="12" font-style="italic" fill="#475569">Generated by SCOS Benchmark Lab</text>\n`;

    svg += `</svg>`;
    fs.writeFileSync(filename, svg);
  }
}

module.exports = ChartGenerator;
